### ISSUE TITLE
Input | Component

### ISSUE THREAD

**Issue by hashemt** [GSG-G7/handyman#26]
## Input Component
- [ ] UI
- [ ] Props

### UI
Some of inputs we will use it:
![input](https://user-images.githubusercontent.com/46839481/65376797-f4240e00-dcac-11e9-9922-a76dc8fa7320.png)

### Props
```javascript
{
    className: String, 
    type: String,
    placeholder: String,
    onChange: function,
    name: String,
}
```

**Comment by AbdallahAmmar96** [comment]
This component is unnecessary
